export const technicalSkills = [
  { id: 1, name: "HTML" },
  { id: 2, name: "CSS" },
  { id: 3, name: "JavaScript" },
  { id: 4, name: "TypeScript" },
  { id: 5, name: "Python" },
  { id: 6, name: "React" },
  { id: 7, name: "Next.js" },
  { id: 8, name: "TailwindCSS" },
  { id: 9, name: "Sass" },
  { id: 10, name: "NeutralinoJS" },
  { id: 11, name: "Node.js" },
  { id: 12, name: "Express" },
  { id: 13, name: "MySQL" },
  { id: 14, name: "PostgreSQL" },
  { id: 15, name: "Prisma" },
  { id: 16, name: "Docker" },
  { id: 17, name: "Figma" },
  { id: 18, name: "Git/GitHub" },
];

export const projects = [
  {
    id: 1,
    image: "../../../../assets/images/bionbe/accueil.png",
    title: "Bionbe",
    subtitle: "Projet de Stage",
  },
  {
    id: 2,
    image: "",
    title: "Aelys",
    subtitle: "Projet de Stage",
  },
  {
    id: 3,
    image: "",
    title: "Bijoux de Soins",
    subtitle: "Projet autonome",
  },
  {
    id: 4,
    image: "",
    title: "Externatic",
    subtitle: "Projet de Formation en Groupe",
  },
  {
    id: 5,
    image: "",
    title: "EcoTripr",
    subtitle: "Projet de Formation en Groupe",
  },
  {
    id: 6,
    image: "",
    title: "FleetGo",
    subtitle: "Projet de Formation en Groupe",
  },
  {
    id: 7,
    image: "",
    title: "WildFit",
    subtitle: "Projet de Formation en Groupe",
  },
  {
    id: 8,
    image: "",
    title: "Wild Code School Biarritz Website",
    subtitle: "Projet de Formation en Groupe",
  },
];

//modifier les descriptions des projets 5, 6, 7 et 8 et rajouter Pets Compagnie
export const ProjectDetails = [
  {
    id: 1,
    Title: "Bionbe",
    Subtitle: "Projet de Stage",
    Description:
      "Ce projet à été réalisé durant de mon stage chez Pic Digital en collaboration avec mon tuteur. C'est un projet que j'ai démarré de zéro. Je devais améliorer la modale de recherche pour le site Bionbe afin que les utilisateurs puissent filtrer leurs recherches facilement et ainsi trouver des activités, des évènements, des clubs et des personnes autour d'eux.",
    TechnologiesTitle: "Les technologies utilisées",
    Technologies: ["Vite", "Typescript", "Sass"],
    Image: "/assets/images/bionbe/accueil.png",
    ImageGallery: [
      "/assets/images/bionbe/accueil.png",
      "/assets/images/bionbe/mobile_accueil.png",
      "/assets/images/bionbe/mobile1.png",
      "/assets/images/bionbe/recherche.png",
      "/assets/images/bionbe/tablette.png",
    ],
  },
  {
    id: 2,
    Title: "Aelys",
    Subtitle: "Projet de Stage",
    Description:
      "Ce projet à été réalisé au cour de mon stage chez Pic Digital en collaboration avec mon tuteur. C'est un projet que j'ai démarré de zéro. Je devais améliorer l'interface et l'utilisation du site pour les employés du magasin Aelys afin qu'ils puissent gérer leuurs commandes facilement. Pour cela j'ai utilisé NeutralinoJs qui m'a permi de concevoir un application bureau compatible avec toute les plateformes, ainsi que React et son framework Vite",
    TechnologiesTitle: "Les technologies utilisées",
    Technologies: ["Vite", "Typescript", "Sass"],
    Image: "/assets/images/aelys/accueil.png",
    ImageGallery: [
      "/assets/images/aelys/accueil.png",
      "/assets/images/aelys/aelys.png",
      "/assets/images/aelys/settings.png",
    ],
  },
  {
    id: 3,
    Title: "Bijoux de Soins",
    Subtitle: "Projet en Autonomie",
    Description:
      "J'ai réalisé ce projet à au cour de ma formation et de mon stage de la conception de la maquette, en passant par la modélisation de la base de donnée jusqu'au développement des fonctionnalités. Il a été nécessaire pour moi afin de reprendre toutes les compétences vu pendant mes précédentes expériences et pratiquer seule. C'est un projet Fullstack que j'ai présenté lors de mon passage du titre de développeur web et web mobile. Il est encoore en cours de construction et reste des fonctionnalités à implémenter telle que la prise de rendez vous. Je suis fière du travaille accomplis jusqu'ici et compte bien continuer à améliorer ce site.",
    TechnologiesTitle: "Les technologies utilisées",
    Technologies: [
      "NextJs",
      "Typescript",
      "Tailwind",
      "Node.js",
      "PostreSQL",
      "Express",
      "Prisma",
      "Docker",
    ],
    Image: "/assets/images/bijoux_desoins/accueil.png",
    ImageGallery: [
      "/assets/images/bijoux_desoins/accueil.png",
      "/assets/images/bijoux_desoins/connexion.png",
      "/assets/images/bijoux_desoins/dashboard.png",
      "/assets/images/bijoux_desoins/home.png",
      "/assets/images/bijoux_desoins/inscription.png",
      "/assets/images/bijoux_desoins/prestations.png",
      "/assets/images/bijoux_desoins/products.png",
      "/assets/images/bijoux_desoins/soins.png",
      "/assets/images/bijoux_desoins/tarifs.png",
      "/assets/images/bijoux_desoins/mobile_contact1.png",
      "/assets/images/bijoux_desoins/mobile_contact.png",
      "/assets/images/bijoux_desoins/mobile_home.png",
      "/assets/images/bijoux_desoins/mobile_contact1.png",
      "/assets/images/bijoux_desoins/mobile_footer.png",
      "/assets/images/bijoux_desoins/mobile_prestations.png",
      "/assets/images/bijoux_desoins/mobile_products.png",
      "/assets/images/bijoux_desoins/mobile_tarifs.png",
      "/assets/images/bijoux_desoins/mobile.png",
    ],
  },

  {
    id: 4,
    Title: "Externatic",
    Subtitle: "Projet de Formartion en Groupe",
    Description:
      "Ce projet à été réalisé au cour de ma formation en groupe de trois sur une durée de 8 semaines. Le but était de mettre en pratique nos connaissances nouvellement asquises. Nous devions construire un site FullStack. Cela nous à permit d'appréhender de nouvelles technologies telles que Prisma et TypeScript",
    TechnologiesTitle: "Les technologies utilisées",
    Technologies: [
      "NextJs",
      "Typescript",
      "Tailwind",
      "Node.js",
      "PostreSQL",
      "Express",
      "Prisma",
      "Docker",
    ],
    Image: "/assets/images/externatic/accueil.png",
    ImageGallery: [
      "/assets/images/externatic/accueil.png",
      "/assets/images/externatic/connection.png",
      "/assets/images/externatic/entreprises.png",
      "/assets/images/externatic/navbar.png",
      "/assets/images/externatic/offres.png",
      "/assets/images/externatic/mobile_accueil.png",
      "/assets/images/externatic/mobile_offres.png",
      "/assets/images/externatic/profile.png",
      "/assets/images/externatic/mobile_footer.png",
      "/assets/images/externatic/navbar_mobile.png",
    ],
  },
  {
    id: 5,
    Title: "EcoTripr",
    Subtitle: "Projet de Formartion en Groupe",
    Description:
      "Ce projet à été réalisé au cour de mon stage chez Pic Digital en collaboration avec mon tuteur. C'est un projet que j'ai démarré de zéro. Je devais améliorer la modale de recherche pour le site Bionbe afin que les utilisateurs puissent filtrer leurs recherches facilement et ainsi trouver des activités, des évènements, des clubs et des personnes autour d'eux.",
    TechnologiesTitle: "Les technologies utilisées",
    Technologies: ["Vite", "Typescript", "Sass"],
    Image: "Chemin_vers_une_image",
    ImageGallery: ["Chemin_vers_image1", "Chemin_vers_image2"],
  },
  {
    id: 6,
    Title: "FleetGo",
    Subtitle: "Projet de Formartion en Groupe",
    Description:
      "Ce projet à été réalisé au cour de mon stage chez Pic Digital en collaboration avec mon tuteur. C'est un projet que j'ai démarré de zéro. Je devais améliorer la modale de recherche pour le site Bionbe afin que les utilisateurs puissent filtrer leurs recherches facilement et ainsi trouver des activités, des évènements, des clubs et des personnes autour d'eux.",
    TechnologiesTitle: "Les technologies utilisées",
    Technologies: ["Vite", "Typescript", "Sass"],
    Image: "Chemin_vers_une_image",
    ImageGallery: ["Chemin_vers_image1", "Chemin_vers_image2"],
  },
  {
    id: 7,
    Title: "WildFit",
    Subtitle: "Projet de Formartion en Groupe",
    Description:
      "Ce projet à été réalisé au cour de mon stage chez Pic Digital en collaboration avec mon tuteur. C'est un projet que j'ai démarré de zéro. Je devais améliorer la modale de recherche pour le site Bionbe afin que les utilisateurs puissent filtrer leurs recherches facilement et ainsi trouver des activités, des évènements, des clubs et des personnes autour d'eux.",
    TechnologiesTitle: "Les technologies utilisées",
    Technologies: ["Vite", "Typescript", "Sass"],
    Image: "Chemin_vers_une_image",
    ImageGallery: ["Chemin_vers_image1", "Chemin_vers_image2"],
  },
  {
    id: 8,
    Title: "Wild Code School Biarritz Website",
    Subtitle: "Projet de Formation en Groupe",
    Description:
      "Ce projet était le premier de ma formation. Il nous a permis de nous familiariser avec les langages de base du développement web (HTML, CSS, JavaScript). Nous l’avons réalisé par groupe de 4 et avons chacun travaillé sur une page différente du site. Pour ma part j’ai réalisé la page contact, avec la création d’une navigation responsive, un formulaire de contact, comprenant quelques animations, une validation du message à la soumission du formulaire, une carte indiquant l’emplacement de l’école, ainsi qu’un Footer avec l’accès aux différents réseaux sociaux de l’école.",
    TechnologiesTitle: "Les technologies utilisées",
    Technologies: ["HTML", "CSS", "JavaScript"],
    Image: "Chemin_vers_une_image",
    ImageGallery: [
      "Chemin_vers_image1",
      "Chemin_vers_image2",
      "Chemin_vers_image3",
    ],
  },
];
