export const Technicalskills = [
  { id: 1, name: "HtML" },
  { id: 2, name: "Css" },
  { id: 3, name: "JS" },
  { id: 4, name: "TS" },
  { id: 5, name: "Python" },
  { id: 6, name: "React" },
  { id: 7, name: "Next.js" },
  { id: 8, name: "tailwind" },
  { id: 9, name: "sass" },
  { id: 10, name: "Nljs" },
  { id: 11, name: "Node.js" },
  { id: 12, name: "Express" },
  { id: 13, name: "MysQL" },
  { id: 14, name: "Postgres" },
  { id: 15, name: "Prisma" },
  { id: 16, name: "docker" },
  { id: 17, name: "Figma" },
  { id: 18, name: "Git" },
  { id: 19, name: "GitHub" },
];

export const Projects = [
  {
    id: 1,
    image: "/assets/images/bionbe/accueil.png",
    title: "Bionbe",
    subtitle: "Projet de stage",
  },
  {
    id: 2,
    image: "/assets/images/aelys/accueil.png",
    title: "Aelys",
    subtitle: "Projet de stage",
  },
  {
    id: 3,
    image: "/assets/images/bijoux_desoins/accueil.png",
    title: "Bijoux de soins",
    subtitle: "Projet autonome",
  },
  {
    id: 4,
    image: "/assets/images/externatic/accueil.png",
    title: "Externatic",
    subtitle: "Projet de Formation en Groupe",
  },
  {
    id: 5,
    image: "/assets/images/ecotripr/accueil.png",
    title: "Ecotripr",
    subtitle: "Projet de Formation en Groupe",
  },
  {
    id: 6,
    image: "",
    title: "FleetGo",
    subtitle: "Projet de Formation en Groupe",
  },
  {
    id: 7,
    image: "",
    title: "WildFit",
    subtitle: "Projet de Formation en Groupe",
  },
  {
    id: 8,
    image: "",
    title: "Wild Code school Biarritz Website",
    subtitle: "Projet de Formation en Groupe",
  },
];

//modifier les descriptions des projets 5, 6, 7 et 8 et rajouter Pets Compagnie
export const Projectdetails = [
  {
    id: 1,
    title: "Bionbe",
    subtitle: "Projet de stage",
    description:
      "Pendant mon stage de six mois chez Pic Digital, j'ai entrepris un projet de trois mois visant à améliorer la modalité de recherche du site Bionbe. Mon objectif principal était de simplifier le filtrage des recherches pour permettre aux utilisateurs de trouver facilement des activités, des événements, des clubs et des personnes dans leur région.",
    technologiestitle: "Les technologies utilisées",
    technologies: ["Vite", "TS", "sass", "Elastic"],
    image: "/assets/images/bionbe/accueil.png",
    imageGallery: [
      "/assets/images/bionbe/accueil.png",
      "/assets/images/bionbe/mobile-accueil.png",
      "/assets/images/bionbe/mobile1.png",
      "/assets/images/bionbe/recherche.png",
      "/assets/images/bionbe/tablette.png",
    ],
  },
  {
    id: 2,
    title: "Aelys",
    subtitle: "Projet de stage",
    description:
      "J'ai réalisé ce projet durant mon stage chez Pic Digital, en collaboration avec mon tuteur. J'ai entrepris ce projet à partir de zéro, avec pour objectif d'améliorer l'interface et l'expérience utilisateur du site destiné aux employés du magasin Aelys, facilitant ainsi la gestion de leurs commandes. Pour atteindre cet objectif, j'ai utilisé NeutralinoJS pour concevoir une application de bureau compatible avec toutes les plateformes. De plus, j'ai intégré React et son framework Vit pour renforcer les fonctionnalités de l'application.",
    technologiestitle: "Les technologies utilisées",
    technologies: ["Vite", "TS", "sass"],
    image: "/assets/images/aelys/accueil.png",
    imageGallery: [
      "/assets/images/aelys/accueil.png",
      "/assets/images/aelys/aelys.png",
      "/assets/images/aelys/settings.png",
    ],
  },
  {
    id: 3,
    title: "Bijoux de soins",
    subtitle: "Projet en Autonomie",
    description:
      "J'ai conçu et développé ce projet durant ma formation et mon stage, en commençant par la création de la maquette, puis la modélisation de la base de données, jusqu'au développement des fonctionnalités. Cette réalisation m'a permis de consolider les compétences acquises au cours de mes expériences passées et de les mettre en pratique de manière autonome. Il s'agit d'un projet Fullstack que j'ai présenté lors de l'obtention de mon titre de développeur web et web mobile. Le projet est encore en cours de développement, certaines fonctionnalités, telles que la prise de rendez-vous, restent à implémenter. Je suis fière du travail accompli jusqu'à présent et j'ai l'intention de poursuivre les améliorations de ce site.",
    technologiestitle: "Les technologies utilisées",
    technologies: [
      "Next.Js",
      "ts",
      "tailwind",
      "Node.js",
      "Postgres",
      "Express",
      "Prisma",
      "docker",
    ],
    image: "/assets/images/bijoux_desoins/accueil.png",
    imageGallery: [
      "/assets/images/bijoux_desoins/accueil.png",
      "/assets/images/bijoux_desoins/connexion.png",
      "/assets/images/bijoux_desoins/dashboard.png",
      "/assets/images/bijoux_desoins/home.png",
      "/assets/images/bijoux_desoins/inscription.png",
      "/assets/images/bijoux_desoins/prestations.png",
      "/assets/images/bijoux_desoins/products.png",
      "/assets/images/bijoux_desoins/soins.png",
      "/assets/images/bijoux_desoins/tarifs.png",
      "/assets/images/bijoux_desoins/mobile_contact1.png",
      "/assets/images/bijoux_desoins/mobile_contact.png",
      "/assets/images/bijoux_desoins/mobile_home.png",
      "/assets/images/bijoux_desoins/mobile_contact1.png",
      "/assets/images/bijoux_desoins/mobile_footer.png",
      "/assets/images/bijoux_desoins/mobile_prestations.png",
      "/assets/images/bijoux_desoins/mobile_products.png",
      "/assets/images/bijoux_desoins/mobile_tarifs.png",
      "/assets/images/bijoux_desoins/mobile.png",
    ],
  },

  {
    id: 4,
    title: "Externatic",
    subtitle: "Projet de Formation en Groupe",
    description:
      "Ce projet a été mené à bien au cours de ma formation en groupe de trois, sur une période de 8 semaines. Notre objectif était de mettre en pratique les connaissances récemment acquises. Notre mission était de concevoir un site Fullstack, ce qui nous a amené à explorer de nouvelles technologies, notamment Prisma et TypeScript.",
    technologiestitle: "Les technologies utilisées",
    technologies: [
      "Next.js",
      "ts",
      "tailwind",
      "Node.js",
      "Postres",
      "Express",
      "Prisma",
      "docker",
    ],
    image: "/assets/images/externatic/accueil.png",
    imageGallery: [
      "/assets/images/externatic/accueil.png",
      "/assets/images/externatic/connection.png",
      "/assets/images/externatic/entreprises.png",
      "/assets/images/externatic/navbar.png",
      "/assets/images/externatic/offres.png",
      "/assets/images/externatic/mobile_accueil.png",
      "/assets/images/externatic/mobile_offres.png",
      "/assets/images/externatic/mobile_profile.png",
      "/assets/images/externatic/mobile_footer.png",
      "/assets/images/externatic/navbar_mobile.png",
    ],
  },
  {
    id: 5,
    title: "Ecotripr",
    subtitle: "Projet de Formation en Groupe",
    description:
      "Ce projet a marqué notre toute première participation à un hackathon en équipe, d'une durée de 48 heures. Notre objectif était de créer un site dynamique avec un accent particulier sur le frontend en utilisant une ou plusieurs API. Le thème du hackathon était 'Le Voyage', et nous avons opté pour une application permettant à l'utilisateur de glisser et déposer sa propre photo sur un arrière-plan représentant un lieu de son choix. Ce projet s'est avéré être une expérience particulièrement stimulante et enrichissante.",
    technologiestitle: "Les technologies utilisées",
    technologies: ["Vite", "TS", "sass"],
    image: "/assets/images/ecotripr/accueil.png",
    imageGallery: [
      "/assets/images/ecotripr/accueil.png",
      "/assets/images/ecotripr/accueil1.png",
      "/assets/images/ecotripr/accueil3.png",
      "/assets/images/ecotripr/choose-destination.png",
      "/assets/images/ecotripr/choose.png",
      "/assets/images/ecotripr/file.png",
      "/assets/images/ecotripr/last-step.png",
    ],
  },
  {
    id: 6,
    title: "FleetGo",
    subtitle: "Projet de Formation en Groupe",
    description:
      "Ce projet a marqué notre deuxième participation à un hackathon en équipe, d'une durée de 72 heures. Notre objectif était de développer une application Fullstack sur le thème d'une agence de location de flotte de véhicules.",
    technologiestitle: "Les technologies utilisées",
    technologies: ["Vite", "TS", "sass"],
    image: "/assets/images/fleetgo/accueil1.png",
    imageGallery: [
      "/assets/images/fleetgo/accueil1.png",
      "/assets/images/fleetgo/accueil2.png",
      "/assets/images/fleetgo/accueil3.png",
      "/assets/images/fleetgo/compte.png",
      "/assets/images/fleetgo/mobile-compte.png",
      "/assets/images/fleetgo/mobile.png",
    ],
  },
  {
    id: 7,
    title: "WildFit",
    subtitle: "Projet de Formation en Groupe",
    description:
      "Ce projet constituait le deuxième volet de ma formation, et nous l'avons réalisé en équipe. Notre principal objectif était de nous familiariser avec les API. En conséquence, nous avons conçu une application dynamique et réactive centrée sur le thème du sport.",
    technologiestitle: "Les technologies utilisées",
    technologies: ["Vite", "TS", "sass"],
    image: "/assets/images/WildFit/accueil.png",
    imageGallery: [
      "/assets/images/WildFit/accueil.png",
      "/assets/images/WildFit/exo.png",
      "/assets/images/WildFit/mobile_accueil.png",
      "/assets/images/WildFit/mobile-exo.png",
      "/assets/images/WildFit/progress.png",
      "/assets/images/WildFit/progress1.png",
    ],
  },
  {
    id: 8,
    title: "WCS Biarritz Website",
    subtitle: "Projet de Formation en Groupe",
    description:
      "Ce projet représentait le tout premier de ma formation. Il a constitué une introduction essentielle aux langages fondamentaux du développement web, tels qu'HTML, CSS et JavaScript. Nous l'avons réalisé en groupe de quatre, chacun se concentrant sur une page différente du site. Mon rôle a été de concevoir la page de contact, comprenant une navigation responsive, un formulaire de contact avec des animations intégrées, une validation du message lors de la soumission du formulaire, une carte indiquant l'emplacement de l'école, ainsi qu'un pied de page permettant l'accès aux différents réseaux sociaux de l'école.",
    technologiestitle: "Les technologies utilisées",
    technologies: ["HTML", "Css", "JS"],
    image: "/assets/images/wsc_siteweb/contact.png",
    imageGallery: [
      "/assets/images/wsc_siteweb/contact.png",
      "/assets/images/wsc_siteweb/mobile_pied_page.png",
      "/assets/images/wsc_siteweb/mobile.png",
      "/assets/images/wsc_siteweb/pied_page.png",
    ],
  },
];

export const Experiences = [
  {
    id: 1,
    name: "Portfolio",
    company: "Projet en autonomie",
    duration: "3 semaines",
    tasks: [
      "• Création d'une maquette Figma, couvrant les formats mobiles et bureau\n",
      "• Développement de l'application en utilisant NextJ.js et TypeScript\n",
      "• Développement du projet avec Prettier et Eslint pour un code propre et organisé\n",
      "• Déploiement du projet sur Vercel\n",
    ],
  },
  {
    id: 2,
    name: "Développeuse Web (Stage)",
    company: "Pic Digital (64)",
    duration: "Mars 2023 - Aout 2023",
    tasks: [
      "• Développement d’application bureau pour la gestion de commandes avec NeutralinoJs, React et Tailwind",
      "• Développement d’une modale de recherche responsive pour la recherche d’activités, d’évènements avec Vite, TypeScript, Sass",
      "• Participation aux sprints, Intégration en équipe, développement de fonctionnalités.",
      "• Compétence en développement frontend, performance, tests, maintenabilité, débogage",
      "• Rédaction et maintenance d’une documentation complète",
    ],
  },
  {
    id: 3,
    name: "Bijoux de Soins",
    company: "Projet en autonomie",
    duration: "Février 2023 - Août 2023",
    tasks: [
      "• Application FullStack et Responsive, Site Institut Bijoux de Soins, présenté pour le Titre DWWM",
      "• Maquette, modélisation de base de données, mis en place d’une API et des routes, développement Frontend",
      "• Figma-NodeJs-PostgreSql-Express-Prisma-Docker TypeScript NextJs-Github-Tailwind",
    ],
  },
  {
    id: 4,
    name: "Projet 3 - Externatic",
    company: "Wild Code School (64)",
    duration: "Décembre 2022 - Février 2023",
    tasks: [
      "• Réalisation d'une application FullStack et Responsive, Site de recherche d’emploi (Projet de groupe)",
      "• Collaboration méthode agile",
      "• Conception d'une maquette reponsive",
      "• Figma-NodeJs-PostgreSql-Express-Prisma-Docker TypeScript-NextJs-Github-Tailwind",
    ],
  },
  {
    id: 5,
    name: "Hackathon 2 - FleetGo",
    company: "Wild Code School (64)",
    duration: "72h00",
    tasks: [
      "• Réalisation d'une application FullStack et Responsive - (Projet de groupe), Site sur la gestion location d’une flotte de véhicule",
      "• Collaboration méthode agile",
      "• Conception d'une maquette reponsive",
      "• Figma-NextJs(Front & Back)-Github-Tailwind-TypeScript",
    ],
  },
  {
    id: 6,
    name: "Hackathon 1 - EcoTripr",
    company: "Wild Code School (64)",
    duration: "48h00",
    tasks: [
      "• Réalisation d'une application Frontend sur le thème du voyage",
      "• Utilisation des API Pixabay & ClipDrop (Projet de groupe)",
      "• Collaboration méthode agile",
      "• Conception d'une maquette reponsive",
      "• React-JS-Github-Tailwind-Figma",
    ],
  },
  {
    id: 7,
    name: "Projet 2 - WildFit",
    company: "Wild Code School (64)",
    duration: "Novembre 2022 - Décembre 2022",
    tasks: [
      "• Réalisation d'une application Frontend et Responsive - (Projet de groupe), Interagir avec une API",
      "• Collaboration méthode agile",
      "• Conception d'une maquette reponsive",
      "• HTML5-CSS-JS-REACT-Tailwind-Git-Github",
    ],
  },
];
